/* config.h Generated by cmake with CMakelists.txt. from config.h.cmake  */

/* Define if you want to enable MPI */
#cmakedefine ENABLE_MPI 

/* Define if you want to use lustre */
#cmakedefine ENABLE_LUSTRE 

/* Define if you want to enable timing */
#cmakedefine ENABLE_TIMING

/* Define if you want to enable checkpoint */
#cmakedefine ENABLE_CHECKPOINT

/* Define if you want to enable profiling */
#cmakedefine ENABLE_PROFILING

/* Define if you want to enable multithread */
#cmakedefine ENABLE_MULTITHREAD

/* Define if compiler supports attributes */
#cmakedefine HAVE_ATTRIBUTE

/* Define if has Cray DRC */
#cmakedefine PDC_HAS_CRAY_DRC

/* Define if use shared server */
#cmakedefine PDC_HAS_SHARED_SERVER

/* Define if closing server by application */
#cmakedefine ENABLE_APP_CLOSE_SERVER

/* Define if wait for data to be fanalized when closing dataset */
#cmakedefine ENABLE_WAIT_DATA

/* Define size of float type */
#cmakedefine VAR_SIZE_FLOAT @VAR_SIZE_FLOAT@

/* Define size of double type */
#cmakedefine VAR_SIZE_DOUBLE @VAR_SIZE_DOUBLE@

/* Define size of char type */
#cmakedefine VAR_SIZE_CHAR @VAR_SIZE_CHAR@

/* Define size of short int type */
#cmakedefine VAR_SIZE_SINT @VAR_SIZE_SINT@

/* Define size of int type */
#cmakedefine VAR_SIZE_INT @VAR_SIZE_INT@

/* Define size of long int type */
#cmakedefine VAR_SIZE_LINT @VAR_SIZE_LINT@

/* Define size of long long int type */
#cmakedefine VAR_SIZE_LLINT @VAR_SIZE_LLINT@

/* Define size of unsigned int type */
#cmakedefine VAR_SIZE_UINT @VAR_SIZE_UINT@

/* Define size of unsigned long int type */
#cmakedefine VAR_SIZE_ULINT @VAR_SIZE_ULINT@

/* Define size of unsigned long long int type */
#cmakedefine VAR_SIZE_ULLINT @VAR_SIZE_ULLINT@

/* Define size of int64_t int type */
#cmakedefine VAR_SIZE_64INT @VAR_SIZE_64INT@

/* Define size of uint64_t int type */
#cmakedefine VAR_SIZE_U64INT @VAR_SIZE_U64INT@
