/* config.h Generated by cmake with CMakelists.txt. from config.h.cmake  */

/* Define if you want to enable MPI */
#cmakedefine ENABLE_MPI 1

/* Define if you want to use lustre */
#cmakedefine ENABLE_LUSTRE 1

/* Define if you want to enable timing */
#cmakedefine ENABLE_TIMING 1

/* Define if you want to enable checkpoint */
#cmakedefine ENABLE_CHECKPOINT 1

/* Define if you want to enable profiling */
#cmakedefine ENABLE_PROFILING 1

/* Define if you want to enable multithread */
#cmakedefine ENABLE_MULTITHREAD 1
