/* config.h Generated by cmake with CMakelists.txt. from config.h.cmake  */

/* Define if you want to enable MPI */
#cmakedefine ENABLE_MPI 

/* Define if you want to use lustre */
#cmakedefine ENABLE_LUSTRE 

/* Define if you want to enable timing */
#cmakedefine ENABLE_TIMING

/* Define if you want to enable checkpoint */
#cmakedefine ENABLE_CHECKPOINT

/* Define if you want to enable profiling */
#cmakedefine ENABLE_PROFILING

/* Define if you want to enable multithread */
#cmakedefine ENABLE_MULTITHREAD

/* Define if has Cray DRC */
#cmakedefine PDC_HAS_CRAY_DRC

/* Define if use shared server */
#cmakedefine PDC_HAS_SHARED_SERVER

/* Define if closing server by application */
#cmakedefine ENABLE_APP_CLOSE_SERVER

/* Define if your compiler supports attributes */
#cmakedefine HAVE_ATTRIBUTE

/* Define if wait for data to be fanalized when closing dataset */
#cmakedefine ENABLE_WAIT_DATA

