name: GitLab

on:
  push:
    branches:
      - develop

jobs:
  sync-with-gitlab:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup git
        run: |
          git config --global user.name "PDC BOT"
          git config --global user.email "pdc@example.com"
    
      - name: Update branch
        run: |
          git fetch origin develop
          git remote add gitlab https://${{ secrets.GITLAB_TOKEN_NAME }}:${{ secrets.GITLAB_TOKEN }}@${{ secrets.GITLAB_URL }}
          git checkout develop
          git push -f gitlab -u develop
